# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3283d73d4653d3f34ee71c2623b7584e71a071ffea9d667cd855a60f0fbd02fcae2930846fe5364c8a1fd0ed51f91c0877dc6f4700868648dd5faa8149eb2f44

test:
  secret_key_base: d278cbc0cdf9432293c22f50f1d89576cb4c8bad631d5c09e132dca9f30fc5fc74879d7696bf9a676e63aa6612c5e03e2efb258f81e35e57c60a1692e36469e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
