# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc4f4f5d9c06a7eced76ced7b352116a0d4d85d09b5d92fc93995fe271988e5ab288fc162bf535bb5d4abab3e5ae4a9d5e127e432a86d66b52e15c3133849d5c

test:
  secret_key_base: 7cd8b9762a7923debb442118c25c1348a2f1b7e2288f06d59fec1b6bca6b094c9d8efcf0f398f8377701dc3346f667152f8b063f5fdbcb9b57df28d52a58abd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
